version: '3.8'
services:
  backend-app:
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
    volumes:
      # Mount the root folder that contains .git      
      - .:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    depends_on:
      - db-server
    networks:
      - app-network
    # Overrides default command so things don't shut down after the process ends.
    environment:
      - PYTHONUNBUFFERED=1
      - POETRY_VIRTUALENVS_IN_PROJECT=1   
      - POETRY_VIRTUALENVS_OPTIONS_NO_PIP='true'
    command: sleep infinity    
  db-server:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network
  frontend-app:
    image: "mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm"    
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    depends_on: 
      - backend-app
    networks:
      - app-network
volumes:
  postgres-data:

networks:
  app-network:
